module.exports = [
  { q: "Who needs the group photo to look balanced?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who already mapped the parking exit?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who says “five more minutes” in every store?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who says “we should leave” at minute twelve?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who makes the Airbnb look like a magazine?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who makes the Airbnb Wi-Fi actually work?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who double-texts, then pretends it was one?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who leaves on read and shows up with snacks?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who turns grocery shopping into a little date?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who turns grocery shopping into a budget line?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who picks the spot for the lighting?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who picks the spot for the parking?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who apologizes when the weather is rude?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who brought the umbrella and called it planning?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who wants to talk it out at 2 a.m.?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who wants to sleep and talk at breakfast?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who remembers your favorite song?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who remembers your car’s last oil change?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who says “let’s try the new place”?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who says “the usual is fine”?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who softens a no with three compliments?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who softens a no with a calendar invite?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who steals the blanket with charm?", a: "Libra woman", b: "Capricorn man" },
  { q: "Who steals the blanket with cold logic?", a: "Libra woman", b: "Capricorn man" },
];
