module.exports = [
  { q: "Who takes one hour to pick a movie?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who already bought the tickets?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who tries eight outfits, then wears black?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who wears the same jacket all week?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who says “you choose” then hates the choice?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who makes a plan and a backup plan?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who is late, but looks cute?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who is ten minutes early and a little mad?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who writes a long text, then deletes it?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who replies “ok” and means I love you?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who wants peace more than being right?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who needs to win the tiny fight?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who takes forty photos for one post?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who takes no photos but remembers the bill?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who could make friends with a chair?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who talks once and that is the speech?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who goes out “just looking” and comes back with bags?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who checks the bank app first?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who wants dessert, a walk, and a new plan?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who wants to be home by ten?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who says sorry just to keep the peace?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who says nothing, then does the dishes?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who overthinks a voice note?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who saves every file in a neat folder?", a: "Libra girl", b: "Capricorn man" },
];
