module.exports = [
  { a: "Mountains", b: "Beaches" },
  { a: "Pani Puri", b: "Pizza" },
  { a: "Fight one horse-sized duck", b: "Fight 100 duck-sized horses" },
  { a: "Rainy day with chai", b: "Cozy night with a blanket" },
  { a: "Cold coffee", b: "Hot chai" },
  { a: "Talk to animals", b: "Speak every human language" },
  { a: "Invisibility", b: "Teleportation" },
  { a: "Biryani with raita", b: "Biryani without raita" },
  { a: "Have a tail", b: "Have antennae on your head" },
  { a: "Early morning workout", b: "Late-night Netflix binge" },
  { a: "Ketchup on everything", b: "No ketchup ever" },
  { a: "Only whisper for a year", b: "Only shout for a year" },
  { a: "Being too hot", b: "Being too cold" },
  { a: "The last bite of your meal", b: "The first sip of your drink" },
  { a: "Same meal every day", b: "Same outfit every day" },
  { a: "Unlimited money", b: "Unlimited time" },
  { a: "Eat the pizza crust first", b: "Save the crust for last" },
  { a: "Walk barefoot on hot sand", b: "Walk barefoot on Lego" },
  { a: "Five minutes late", b: "Thirty minutes early" },
  { a: "Maggi with cheese", b: "Maggi with egg" },
  { a: "A horror movie", b: "A crying emotional movie" },
  { a: "Window seat", b: "Aisle seat" },
  { a: "Road trip with no music", b: "Road trip with no AC" },
  { a: "Coffee date", b: "Ice cream date" },
];
