module.exports = [
  { q: "Who orders for both, then asks if it is okay?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who reads the menu like a contract?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who turns a quick errand into a whole vibe?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who turns a whole vibe into a quick errand?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who needs the table to look pretty before eating?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who eats first and fixes the wobbly chair?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who says “whatever you want” with a whole opinion?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who says “pick one” and actually means it?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who soft-launches a fight with a sigh?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who ends a fight by fixing something?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who remembers every compliment from 2019?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who remembers every due date this month?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who flirts by making eye contact with everyone?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who flirts by opening the car door once?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who buys candles “for the mood”?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who buys batteries “just in case”?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who wants one more song at the party?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who already knows where the keys are?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who sends three hearts and a question mark?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who sends “k” and is fully committed?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who redecorates the room in their head?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who renegotiates the rent in their head?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who says “let’s stay out” at midnight?", a: "Libra girl", b: "Capricorn man" },
  { q: "Who says “tomorrow is early” at 9 p.m.?", a: "Libra girl", b: "Capricorn man" },
];
